CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  username VARCHAR NOT NULL,
  password TEXT NOT NULL
);

INSERT INTO users (name, email, username, password)
VALUES
    ('Biz Hight', 'elizabeth.biz.hight@gmail.com', 'biz_codes', 'Go4Admin!'),
    ('Demo user', 'thisisafakeemail@gmail.com', 'demo_user', 'Go4Demo!');