CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

INSERT INTO users (name, username, password)
VALUES
    ('Biz Hight', 'elizabeth.biz.hight@gmail.com', 'Go4Admin!'),
    ('Demo user', 'demo.email@gmail.com', 'Go4Demo!');