CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);

INSERT INTO users (name, email, username, password)
VALUES
    ('Biz Hight', 'elizabeth.biz.hight@gmail.com', 'biz_codes', '@Go2Future'),
    ('Demo user', 'thisisafakeemail@gmail.com', 'demo_user', '@Go2Demo');