CREATE TABLE tools (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tool_name VARCHAR(255) NOT NULL,
    details TEXT,
    quantity INTEGER NOT NULL
);

ALTER TABLE tools
    ADD COLUMN
        user_id INTEGER REFERENCES users(id)
        ON DELETE CASCADE NOT NULL;

INSERT INTO tools (tool_name, details, quantity, user_id)
    VALUES
        ('hammer', 'small, yellow grip', 2, 2),
        ('paintbrush', 'large', 10, 2),
        ('sandpaper', 'fine', 5, 2),
        ('sewing machine', 'singer', 1, 2);
