CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_name VARCHAR(255) NOT NULL,
    supplies_needed TEXT,
    tools_needed TEXT,
    instructions TEXT,
    delivery_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    done BOOLEAN
);

ALTER TABLE projects
    ADD COLUMN
        user_id INTEGER REFERENCES users(id)
        ON DELETE CASCADE NOT NULL;

INSERT INTO projects (project_name, supplies_needed, tools_needed, instructions, delivery_date, done, user_id)
    VALUES
        ('Raised Bed', 'chicken wire, screws, staples, wood', 'drill, staple gun', '...', '2019-07-04', true, 2),
        ('Stormy Pants', 'blue thread, jersey knit cotton, pattern', 'marking pen, pins, scissors, sewing machine, sewing machine needle', '...', '2021-09-30', false, 2);
                    